### ISSUE TITLE
New frame is opened when "switch-to-buffer-other-window" in edit-window

### ISSUE THREAD

**Issue by kimim** [ecb-home/ecb#15] opened 2015-08-14 08:21 UTC
"switch-to-buffer-other-window" in edit-window will open the buffer in a new frame while not in a split window. 
This cause org-open-at-point, click on grep result, click in dired buffer to open new frame for the content.
I found that pop-to-buffer advised in ecb-layout.el probably is the root cause. 
Seems only happen in new version of emacs(25.0.50.1) on my machine.

**Comment by trashofmasters** [comment] 2015-08-28 11:33
I believe this report relates to #8. As far as I could find ECB seems to be ignoring Emacs [window management](http://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html#Window-Choice) configuration and causing a new frame to be opened every time a `*-other-window` function is called.

**Comment by ware** [comment] 2016-01-02 02:04
I'll be looking into this as part of #8.  That said, please keep in mind that Emacs 25.0.50.1 is pre-release.  The latest official release is 24.5.

**Comment by ware** [comment] 2016-12-31 01:51
Closing this as a duplicate of Issue #8.

**Closed by ware** 2016-12-31 01:51 UTC
